services:
  postgres-db:
    image: postgres:15-alpine
    container_name: library-postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=library_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: